services:
  dotnet-server:
    image: dotnet-server
    container_name: dotnet-server
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SecurePassword123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
    volumes:
      - ./shared:/app/shared
      - ${USERPROFILE}/.aspnet/https:/root/.aspnet/https/

  python-app:
    image: python-3.11-dotnet-9-torch-cuda-user
    container_name: python-app
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
    volumes:
      - ./shared:/app/shared

  plantuml:
    image: plantuml-1.2025.2
    container_name: plantuml
    volumes:
      - ./shared:/app/shared