# Use Debian as the base image
FROM python:3.11.11-bullseye

# Set environment variables
ENV DOTNET_RUNNING_IN_CONTAINER=true \
    DOTNET_VERSION=9.0.3 \
    DOTNET_SDK_VERSION=9.0.202 \
    DOTNET_USE_POLLING_FILE_WATCHER=true \
    NUGET_XMLDOC_MODE=skip \
    POWERSHELL_DISTRIBUTION_CHANNEL=PSDocker-DotnetSDK-Debian-11

# Install necessary packages and dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       curl \
       apt-transport-https \
       gnupg2 \
       ca-certificates \
       git \
       build-essential \
       cmake \
       libssl-dev \
       zlib1g-dev \
       libbz2-dev \
       liblz4-dev \
       libsnappy-dev \
       libzstd-dev \
    && rm -rf /var/lib/apt/lists/*

# Install .NET SDK and runtime
RUN curl -fSL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-x64.tar.gz \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet \
    && rm dotnet.tar.gz

# Install PowerShell
RUN powershell_version=7.2.23 \
    && curl -sSL https://github.com/PowerShell/PowerShell/releases/download/v${powershell_version}/powershell-${powershell_version}-linux-x64.tar.gz -o /tmp/powershell.tar.gz \
    && mkdir -p /opt/microsoft/powershell/${powershell_version} \
    && tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/${powershell_version} \
    && ln -s /opt/microsoft/powershell/${powershell_version}/pwsh /usr/bin/pwsh \
    && chmod +x /usr/bin/pwsh \
    && rm /tmp/powershell.tar.gz

# Set the working directory
WORKDIR /app

# Set the default command to bash
CMD ["tail", "-f", "/dev/null"]