FROM nvcr.io/nvidia/pytorch:24.10-py3
WORKDIR /app
COPY requirements.txt .
RUN apt-get update && apt-get install -y graphviz graphviz-dev
#RUN pip install -r requirements.txt
CMD ["tail", "-f", "/dev/null"]
