FROM dotnet-sdk-python-environment:latest
WORKDIR /app
COPY requirements.txt .
COPY requirements2.txt .

# Install necessary packages
RUN apk add --no-cache \
    python3-dev \
    g++ \
    musl-dev \
    linux-headers \
    openblas-dev

RUN apk add --no-cache \
    build-base \
    libffi-dev \
    openblas-dev \
    freetype-dev \
    gfortran \
    lapack-dev \
    cairo-dev \
    pango-dev \
    jpeg-dev \
    zlib-dev \
    libpng-dev \
    libxml2-dev \
    libxslt-dev \
    libmagic \
    libwebp-dev \
    tiff-dev \
    openssl-dev \
    musl-dev \
    libjpeg-turbo-dev \
    ffmpeg \
    poppler-utils \
    poppler-data \
    poppler \
    postgresql-dev \
    libpq \
    graphviz \
    py3-lxml \
    libxml2-dev \
    libxslt-dev 

# Install pip
RUN apk add --no-cache python3 py3-pip

# Configure pip
RUN python3 -m pip config set global.break-system-packages true

# Install numpy
RUN pip install --no-cache-dir numpy==1.22.4

# Install PyTorch
RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

# Install docx2txt
RUN apk update && \
    apk add --no-cache python3 py3-pip build-base wget && \
    wget https://files.pythonhosted.org/packages/7d/7d/60ee3f2b16d9bfdfa72e8599470a2c1a5b759cb113c6fe1006be28359327/docx2txt-0.8.tar.gz && \
    tar -xzf docx2txt-0.8.tar.gz && \
    cd docx2txt-0.8 && \
    sed -i 's/description-file/description_file/' setup.cfg && \
    python3 setup.py bdist_wheel && \
    pip install --break-system-packages dist/docx2txt-0.8-py3-none-any.whl && \
    cd .. && \
    rm -rf docx2txt-0.8 && \
    rm docx2txt-0.8.tar.gz

# Install Flask-CacheBuster
RUN apk update && \
    apk add --no-cache python3 py3-pip build-base wget && \
    wget https://files.pythonhosted.org/packages/74/47/f3e1fedfaad965c81c2f17234636d72f71450f1b4522ca26d2b7eb4a0a74/Flask-CacheBuster-1.0.0.tar.gz && \
    tar -xzf Flask-CacheBuster-1.0.0.tar.gz && \
    cd Flask-CacheBuster-1.0.0 && \
    sed -i 's/description-file/description_file/' setup.cfg && \
    python3 setup.py bdist_wheel && \
    pip install --break-system-packages dist/Flask_CacheBuster-1.0.0-py3-none-any.whl && \
    cd .. && \
    rm -rf Flask-CacheBuster-1.0.0 && \
    rm Flask-CacheBuster-1.0.0.tar.gz 

# Install fpdf
RUN apk update && \
    apk add --no-cache python3 py3-pip build-base wget && \
    pip3 install build && \
    wget https://files.pythonhosted.org/packages/37/c6/608a9e6c172bf9124aa687ec8b9f0e8e5d697d59a5f4fad0e2d5ec2a7556/fpdf-1.7.2.tar.gz && \
    tar -xzf fpdf-1.7.2.tar.gz && \
    cd fpdf-1.7.2 && \
    sed -i 's/description-file/description_file/' setup.cfg && \
    python3 -m build && \
    pip3 install --break-system-packages dist/fpdf-1.7.2-py2.py3-none-any.whl && \
    cd .. && \
    rm -rf fpdf-1.7.2 && \
    rm fpdf-1.7.2.tar.gz

# Uncomment if you need to install additional requirements
RUN pip install --no-cache-dir -r requirements2.txt