FROM my-torch-codeinterpreter:0.1

# Set environment variables
ENV ASPNETCORE_URLS= \
    DOTNET_RUNNING_IN_CONTAINER=true \
    DOTNET_VERSION=6.0.36 \
    DOTNET_SDK_VERSION=6.0.428 \
    DOTNET_USE_POLLING_FILE_WATCHER=true \
    NUGET_XMLDOC_MODE=skip \
    POWERSHELL_DISTRIBUTION_CHANNEL=PSDocker-DotnetSDK-Debian-11

# Install necessary packages and dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       curl \
       apt-transport-https \
       gnupg2 \
       ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Install .NET SDK and runtime
RUN curl -fSL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-x64.tar.gz \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet \
    && rm dotnet.tar.gz

# Install ASP.NET Core runtime
RUN curl -o aspnetcore-runtime.tar.gz https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/6.0.36/aspnetcore-runtime-6.0.36-linux-x64.tar.gz && tar -xzf aspnetcore-runtime.tar.gz \
    && mkdir -p /usr/share/dotnet/shared/Microsoft.AspNetCore.App/6.0.36 \
    && tar -zxf aspnetcore-runtime.tar.gz -C /usr/share/dotnet/shared/Microsoft.AspNetCore.App/6.0.36 \
    && rm aspnetcore-runtime.tar.gz

# Install PowerShell
RUN powershell_version=7.2.23 \
    && curl -sSL https://github.com/PowerShell/PowerShell/releases/download/v${powershell_version}/powershell-${powershell_version}-linux-x64.tar.gz -o /tmp/powershell.tar.gz \
    && mkdir -p /opt/microsoft/powershell/${powershell_version} \
    && tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/${powershell_version} \
    && ln -s /opt/microsoft/powershell/${powershell_version}/pwsh /usr/bin/pwsh \
    && rm /tmp/powershell.tar.gz

# Set the default command to bash
CMD ["tail", "-f", "/dev/null"]