FROM dotnet-9.0-python-3.11

WORKDIR /app
COPY requirements.txt .

RUN pip install --upgrade pip

# Install dependencies and Python 3.11 from the official repositories
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        graphviz \
        graphviz-dev \
        build-essential \
        cmake \
        libopenblas-dev \
        liblapack-dev \
        libboost-python-dev \
        python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables for Metal Performance Shaders
ENV PYTORCH_ENABLE_MPS_FALLBACK=1
ENV PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0

RUN pip install torch==2.3.1 -f https://download.pytorch.org/whl/torch_stable.html && \
    pip install torchaudio==2.3.1 -f https://download.pytorch.org/whl/torch_stable.html

# Added the following dependency so that dependencies in requirements.txt can be installed without issues.
RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    && rm -rf /var/lib/apt/lists/*

# Add environment variables so pip install can find GDAL
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal
ENV GDAL_VERSION=3.2.2
RUN pip install --no-cache-dir -r requirements.txt

SHELL ["/bin/bash", "-c"]
CMD ["tail", "-f", "/dev/null"]

