# Use the official .NET SDK image
FROM my-dotnet-sdk:6.0

# Set the working directory inside the container
WORKDIR /workspace

# Install dependencies for building Python from source
RUN apk update && \
    apk add --no-cache \
    wget \
    build-base \
    openssl \
    openssl-dev \
    zlib-dev \
    ncurses-dev \
    readline-dev \
    sqlite-dev \
    gdbm-dev \
    db-dev \
    bzip2-dev \
    expat-dev \
    xz-dev \
    tk-dev \
    libffi-dev \
    git

RUN git config --global user.name "Your Name" && \
    git config --global user.email "your.email@example.com"

RUN wget https://www.python.org/ftp/python/3.11.11/Python-3.11.11.tgz && \
    tar xzf Python-3.11.11.tgz && \
    cd Python-3.11.11 && \
    ./configure --enable-optimizations && \
    make -j$(nproc) && \
    make altinstall && \
    cd .. && \
    rm -rf Python-3.11.11 Python-3.11.11.tgz

ENV PATH="/usr/local/bin:${PATH}"

RUN ln -s /usr/local/bin/python3.11 /usr/local/bin/py && \
    ln -s /usr/local/bin/pip3.11 /usr/local/bin/pip

HEALTHCHECK CMD python3.11 --version || exit 1

CMD ["tail", "-f", "/dev/null"]