FROM dotnet-9.0-python-3.11

WORKDIR /app
COPY requirements.txt .

RUN pip install --upgrade pip

# Install dependencies and Python 3.11 from the official repositories
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        graphviz \
        graphviz-dev \
        build-essential \
        cmake \
        libopenblas-dev \
        liblapack-dev \
        libboost-python-dev \
        python3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install torch==2.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html && \
    pip install torchaudio==2.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
    
RUN pip install --no-cache-dir -r requirements.txt
SHELL ["/bin/bash", "-c"]
CMD ["tail", "-f", "/dev/null"]